apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cabot
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cabot
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: web
        imagePullPolicy: Always
        image: cabotapp/cabot:0.10.8
        # image: gcr.io/prod-edc/cabot:latest
        command: ["sh", "-c", "cabot migrate && gunicorn cabot.wsgi:application -b 0.0.0.0:5000 --workers=5"]
        ports:
          - containerPort: 5000
        env:
          - name: GRAPHITE_API
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: graphite_url
          - name: GRAPHITE_USER
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: graphite_user
          - name: GRAPHITE_PASS
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: graphite_pass
          - name: HIPCHAT_API_KEY
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: hipchat_api_key
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: twilio_account_sid
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: twilio_token
          - name: TWILIO_OUTGOING_NUMBER
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: twilio_phone
          - name: ADMIN_EMAIL
            value: ekampf@ebates.com
          - name: TIME_ZONE
            value: US/Pacific
          - name: HIPCHAT_ALERT_ROOM
            value: "3972862"
          - name: CABOT_PLUGINS_ENABLED
            value: cabot_alert_hipchat,cabot_alert_twilio,cabot_alert_email,cabot_alert_slack
          - name: DJANGO_SETTINGS_MODULE
            value: cabot.settings
          - name: DATABASE_URL
            value: postgres://postgres@127.0.0.1:5432/postgres
          - name: CELERY_BROKER_URL
            value: amqp://guest:guest@127.0.0.1:5672//
          - name: LOG_FILE
            value: /dev/null
          - name: HTTP_USER_AGENT
            value: Cabot
          - name: WWW_HTTP_HOST
            value: cabot.ebatesedc.com
          - name: WWW_SCHEME
            value: http
        livenessProbe:
           tcpSocket:
             port: 5000
        readinessProbe:
           tcpSocket:
             port: 5000
      - name: worker
        imagePullPolicy: Always
        image: cabotapp/cabot:0.10.8
        command: ["celery", "worker", "-A", "cabot", "--loglevel=DEBUG",  "--concurrency=16", "-Ofair"]
        env:
          - name: SKIP_INIT
            value: "1"
          - name: WAIT_FOR_MIGRATIONS
            value: "1"
      - name: beat
        imagePullPolicy: Always
        image: cabotapp/cabot:0.10.8
        command: ["celery", "beat", "-A", "cabot", "--loglevel=DEBUG"]
        env:
          - name: SKIP_INIT
            value: "1"
          - name: WAIT_FOR_MIGRATIONS
            value: "1"
      - image: postgres:9.6.3-alpine
        name: postgres
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        env:
          - name: PGDATA
            value: /var/lib/postgresql/cabot/pgdata
          - name: POD_IP
            valueFrom: { fieldRef: { fieldPath: status.podIP } }
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 25
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
          - name: cabot-persist
            mountPath: /var/lib/postgresql/cabot:rw
      - image: rabbitmq:3.6-alpine
        name: rabbitmq
        imagePullPolicy: Always
        ports:
          - containerPort: 5672
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
      volumes:
      - name: cabot-persist
        gcePersistentDisk:
          pdName: cabot-k8s
          fsType: ext4
