# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0003_auto_20170201_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='data',
            field=models.TextField(blank=True, help_text=b'HTTP request data', null=True),
        ),
    ]
